<?php

namespace AppBundle\Repository;

/**
 * ApCardRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class ApCardRepository extends \Doctrine\ORM\EntityRepository
{
}
