<?php

namespace AppBundle\Repository;

/**
 * ApEventDetailRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class ApEventDetailRepository extends \Doctrine\ORM\EntityRepository
{
}
