<?php

namespace AppBundle\Repository;

/**
 * ApEventHeaderRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class ApEventHeaderRepository extends \Doctrine\ORM\EntityRepository
{
}
