<?php

namespace AppBundle\Repository;

/**
 * ApEventRaffleRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class ApEventRaffleRepository extends \Doctrine\ORM\EntityRepository
{
}
