<?php

namespace AppBundle\Repository;

/**
 * AssistanceDetailRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class AssistanceDetailRepository extends \Doctrine\ORM\EntityRepository
{
}
