<?php

namespace AppBundle\Repository;

/**
 * AssistanceTransactionRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class AssistanceTransactionRepository extends \Doctrine\ORM\EntityRepository
{
}
