<?php

namespace AppBundle\Repository;

/**
 * AssistanceSummaryRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class AssistanceSummaryRepository extends \Doctrine\ORM\EntityRepository
{
}
