<?php

namespace AppBundle\Repository;

/**
 * AssistanceHeaderRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class AssistanceHeaderRepository extends \Doctrine\ORM\EntityRepository
{
}
