<?php

namespace AppBundle\Repository;

/**
 * AssistanceProfileRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class AssistanceProfileRepository extends \Doctrine\ORM\EntityRepository
{
}
