<?php

namespace AppBundle\Repository;

/**
 * AttendanceProfileRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class AttendanceProfileRepository extends \Doctrine\ORM\EntityRepository
{
}
