<?php

namespace AppBundle\Repository;

/**
 * AttendanceAssignmentRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class AttendanceAssignmentRepository extends \Doctrine\ORM\EntityRepository
{
}
