<?php

namespace AppBundle\Repository;

/**
 * DataUpdateDetailRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class DataUpdateDetailRepository extends \Doctrine\ORM\EntityRepository
{
}
