<?php

namespace AppBundle\Repository;

/**
 * DataUpdateHeaderRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class DataUpdateHeaderRepository extends \Doctrine\ORM\EntityRepository
{
}
