<?php

namespace AppBundle\Repository;

/**
 * DataInquiryRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class DataInquiryRepository extends \Doctrine\ORM\EntityRepository
{
}
