<?php

namespace AppBundle\Repository;

/**
 * EmployeeDirectoryRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class EmployeeDirectoryRepository extends \Doctrine\ORM\EntityRepository
{
}
