<?php

namespace AppBundle\Repository;

/**
 * EventRaffleWinnerRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class EventRAffleWinnerRepository extends \Doctrine\ORM\EntityRepository
{
}
