<?php

namespace AppBundle\Repository;

/**
 * FieldUploadDtlRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class FieldUploadDtlRepository extends \Doctrine\ORM\EntityRepository
{
}
