<?php

namespace AppBundle\Repository;

/**
 * FieldUploadHdrRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class FieldUploadHdrRepository extends \Doctrine\ORM\EntityRepository
{
}
