<?php

namespace AppBundle\Repository;

/**
 * FinancialMedRequirementsRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class FinancialMedRequirementsRepository extends \Doctrine\ORM\EntityRepository
{
}
