<?php

namespace AppBundle\Repository;

/**
 * FinancialAssistanceAggreClosingDtlRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class FinancialAssistanceAggreClosingDtlRepository extends \Doctrine\ORM\EntityRepository
{
}
