<?php

namespace AppBundle\Repository;

/**
 * FinancialAssistanceHeaderRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class FinancialAssistanceHeaderRepository extends \Doctrine\ORM\EntityRepository
{
}
