<?php

namespace AppBundle\Repository;

/**
 * FinancialAssistanceDailyClosingHdrRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class FinancialAssistanceDailyClosingHdrRepository extends \Doctrine\ORM\EntityRepository
{
}
