<?php

namespace AppBundle\Repository;

/**
 * FinancialAssistanceDailyClosingDtlRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class FinancialAssistanceDailyClosingDtlRepository extends \Doctrine\ORM\EntityRepository
{
}
