<?php

namespace AppBundle\Repository;

/**
 * FinancialAssistancePendingClosingDtlRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class FinancialAssistancePendingClosingDtlRepository extends \Doctrine\ORM\EntityRepository
{
}
