<?php

namespace AppBundle\Repository;

/**
 * FormStatusRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class FormStatusRepository extends \Doctrine\ORM\EntityRepository
{
}
