<?php

namespace AppBundle\Repository;

/**
 * GroupPermissionRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class GroupPermissionRepository extends \Doctrine\ORM\EntityRepository
{
    public function checkGroupPermission($attribute, $group, $module)
    {
        $em = $this->getEntityManager();
        $query = $em->createQuery("SELECT gp FROM AppBundle:GroupPermission gp 
                                  JOIN gp.permission p 
                                  JOIN p.moduleId m 
                                  WHERE gp.groupId = :groupId 
                                  AND p.permissionName = :permissionName 
                                  AND m.moduleName = :moduleName")
                    ->setParameters(array("groupId" => $group,"permissionName" => $attribute, "moduleName" => $module));

        return $query;
    }
}
