<?php

namespace AppBundle\Repository;

/**
 * GroupAssistanceRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class GroupAssistanceRepository extends \Doctrine\ORM\EntityRepository
{
}
