<?php

namespace AppBundle\Repository;

/**
 * HouseholdHeaderRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class HouseholdHeaderRepository extends \Doctrine\ORM\EntityRepository
{
}
