<?php

namespace AppBundle\Repository;

/**
 * HouseholdDetailRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class HouseholdDetailRepository extends \Doctrine\ORM\EntityRepository
{
}
