<?php

namespace AppBundle\Repository;

/**
 * IdRequestHeaderRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class IdRequestHeaderRepository extends \Doctrine\ORM\EntityRepository
{
}
