<?php

namespace AppBundle\Repository;

/**
 * IdRequestDetailRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class IdRequestDetailRepository extends \Doctrine\ORM\EntityRepository
{
}
