<?php

namespace AppBundle\Repository;

/**
 * KfcAttendanceDetailRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class KfcAttendanceDetailRepository extends \Doctrine\ORM\EntityRepository
{
}
