<?php

namespace AppBundle\Repository;

/**
 * KfcAttendanceRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class KfcAttendanceRepository extends \Doctrine\ORM\EntityRepository
{
}
