<?php

namespace AppBundle\Repository;

/**
 * LocationAssignmentRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class LocationAssignmentRepository extends \Doctrine\ORM\EntityRepository
{
}
