<?php

namespace AppBundle\Repository;

/**
 * MergedProfileRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class MergedProfileRepository extends \Doctrine\ORM\EntityRepository
{
}
