<?php

namespace AppBundle\Repository;

/**
 * OrganizationHierarchyRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class OrganizationHierarchyRepository extends \Doctrine\ORM\EntityRepository
{
}
