<?php

namespace AppBundle\Repository;

/**
 * PendingVoterRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class PendingVoterRepository extends \Doctrine\ORM\EntityRepository
{
}
