<?php

namespace AppBundle\Repository;

/**
 * PhotoUploadSummaryRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class PhotoUploadSummaryRepository extends \Doctrine\ORM\EntityRepository
{
}
