<?php

namespace AppBundle\Repository;

/**
 * ProjectPrintHeaderRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class ProjectPrintHeaderRepository extends \Doctrine\ORM\EntityRepository
{
}
