<?php

namespace AppBundle\Repository;

/**
 * ProjectVoterSummaryRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class ProjectVoterSummaryRepository extends \Doctrine\ORM\EntityRepository
{
}
