<?php

namespace AppBundle\Repository;

/**
 * ProjectEventHeaderRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class ProjectEventHeaderRepository extends \Doctrine\ORM\EntityRepository
{
}
