<?php

namespace AppBundle\Repository;

/**
 * ProjectVoterSummaryAssignedRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class ProjectVoterSummaryAssignedRepository extends \Doctrine\ORM\EntityRepository
{
}
