<?php

namespace AppBundle\Repository;

/**
 * ProjectClaimStubHeaderRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class ProjectClaimStubHeaderRepository extends \Doctrine\ORM\EntityRepository
{
}
