<?php

namespace AppBundle\Repository;

/**
 * ProjectEventDetailRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class ProjectEventDetailRepository extends \Doctrine\ORM\EntityRepository
{
}
