<?php

namespace AppBundle\Repository;

/**
 * ProjectPrintDetailRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class ProjectPrintDetailRepository extends \Doctrine\ORM\EntityRepository
{
}
