<?php

namespace AppBundle\Repository;

/**
 * ProjectClaimStubDetailRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class ProjectClaimStubDetailRepository extends \Doctrine\ORM\EntityRepository
{
}
