<?php

namespace AppBundle\Repository;

/**
 * RecruitementHeaderRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class RecruitmentHeaderRepository extends \Doctrine\ORM\EntityRepository
{
}
