<?php

namespace AppBundle\Repository;

/**
 * RecruitmentSpecialRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class RecruitmentSpecialRepository extends \Doctrine\ORM\EntityRepository
{
}
