<?php

namespace AppBundle\Repository;

/**
 * RecruitementDetailRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class RecruitmentDetailRepository extends \Doctrine\ORM\EntityRepository
{
}
