<?php

namespace AppBundle\Repository;

/**
 * RecruitmentSummaryRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class RecruitmentSummaryRepository extends \Doctrine\ORM\EntityRepository
{
}
