<?php

namespace AppBundle\Repository;

/**
 * RenewedIdRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class RenewedIdRepository extends \Doctrine\ORM\EntityRepository
{
}
