<?php

namespace AppBundle\Repository;

/**
 * SendSmsRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class SendSmsRepository extends \Doctrine\ORM\EntityRepository
{
}
