<?php

namespace AppBundle\Repository;

/**
 * SmsTemplateRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class SmsTemplateRepository extends \Doctrine\ORM\EntityRepository
{
}
