<?php

namespace AppBundle\Repository;

/**
 * SpecialOperationPhotosRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class SpecialOperationPhotosRepository extends \Doctrine\ORM\EntityRepository
{
}
