<?php

namespace AppBundle\Repository;

/**
 * SpecialOptDetailRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class SpecialOptDetailRepository extends \Doctrine\ORM\EntityRepository
{
}
