<?php

namespace AppBundle\Repository;

/**
 * SpecialOperationHeaderRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class SpecialOperationHeaderRepository extends \Doctrine\ORM\EntityRepository
{
}
