<?php

namespace AppBundle\Repository;

/**
 * SpecialOptHeaderRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class SpecialOptHeaderRepository extends \Doctrine\ORM\EntityRepository
{
}
