<?php

namespace AppBundle\Repository;

/**
 * SpecialOperationDetailRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class SpecialOperationDetailRepository extends \Doctrine\ORM\EntityRepository
{
}
