<?php

namespace AppBundle\Repository;

/**
 * StubDetailRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class StubDetailRepository extends \Doctrine\ORM\EntityRepository
{
}
