<?php

namespace AppBundle\Repository;

/**
 * StubHeaderRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class StubHeaderRepository extends \Doctrine\ORM\EntityRepository
{
}
