<?php

namespace AppBundle\Repository;

/**
 * TempBcbpProfileRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class TempBcbpProfileRepository extends \Doctrine\ORM\EntityRepository
{
}
