<?php

namespace AppBundle\Repository;

/**
 * TupadTransactionRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class TupadTransactionRepository extends \Doctrine\ORM\EntityRepository
{
}
