<?php

namespace AppBundle\Repository;

/**
 * UserAccessRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class UserAccessRepository extends \Doctrine\ORM\EntityRepository
{
}
