<?php

namespace AppBundle\Repository;

/**
 * VoterNetworkRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class VoterNetworkRepository extends \Doctrine\ORM\EntityRepository
{
}
