<?php

namespace AppBundle\Repository;

/**
 * VoterSummaryRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class VoterSummaryRepository extends \Doctrine\ORM\EntityRepository
{
}
