<?php

namespace AppBundle\Repository;

/**
 * VoterStatusRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class VoterStatusRepository extends \Doctrine\ORM\EntityRepository
{
}
