<?php

namespace AppBundle\Repository;

/**
 * VoterAssistanceSummaryRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class VoterAssistanceSummaryRepository extends \Doctrine\ORM\EntityRepository
{
}
