<?php

namespace AppBundle\Repository;

/**
 * VoterHistoryRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class VoterHistoryRepository extends \Doctrine\ORM\EntityRepository
{
}
