<?php

namespace AppBundle\Repository;

/**
 * VoterAssistanceRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class VoterAssistanceRepository extends \Doctrine\ORM\EntityRepository
{
}
