<?php

namespace AppBundle\Repository;

/**
 * VoterRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class VoterRepository extends \Doctrine\ORM\EntityRepository
{
}
