<?php

namespace AppBundle\Repository;

/**
 * VoterApprovalHdrRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class VoterApprovalHdrRepository extends \Doctrine\ORM\EntityRepository
{
}
