<?php

namespace AppBundle\Repository;

/**
 * VoterHeaderRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class VoterHeaderRepository extends \Doctrine\ORM\EntityRepository
{
}
