<?php

namespace AppBundle\Repository;

/**
 * VoterApprovalDtlRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class VoterApprovalDtlRepository extends \Doctrine\ORM\EntityRepository
{
}
